"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-05 14:20:16.695436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_path', sa.Text(), nullable=False),
    sa.Column('rounds_processed', sa.Integer(), nullable=False),
    sa.Column('matches_processed', sa.Integer(), nullable=False),
    sa.Column('records_inserted', sa.Integer(), nullable=False),
    sa.Column('records_updated', sa.Integer(), nullable=False),
    sa.Column('records_unchanged', sa.Integer(), nullable=False),
    sa.Column('observations_created', sa.Integer(), nullable=False),
    sa.Column('issues_created', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running','success','failed')", name=op.f('ck_ingestion_runs_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    op.create_table('seasons',
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seasons')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_seasons_source_external_id'))
    )
    op.create_table('competitions',
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_competitions_season_id_seasons')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competitions')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_competitions_source_external_id'))
    )
    op.create_index(op.f('ix_competitions_season_id'), 'competitions', ['season_id'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_data_quality_issues_ingestion_run_id_ingestion_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_quality_issues'))
    )
    op.create_index(op.f('ix_data_quality_issues_ingestion_run_id'), 'data_quality_issues', ['ingestion_run_id'], unique=False)
    op.create_table('competition_groups',
    sa.Column('competition_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['competition_id'], ['competitions.id'], name=op.f('fk_competition_groups_competition_id_competitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_competition_groups')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_competition_groups_source_external_id'))
    )
    op.create_index(op.f('ix_competition_groups_competition_id'), 'competition_groups', ['competition_id'], unique=False)
    op.create_table('rounds',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('visible_label', sa.String(length=64), nullable=False),
    sa.Column('visible_number', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['competition_groups.id'], name=op.f('fk_rounds_group_id_competition_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rounds')),
    sa.UniqueConstraint('group_id', 'external_id', name=op.f('uq_rounds_group_id_external_id')),
    sa.UniqueConstraint('id', 'group_id', name=op.f('uq_rounds_id_group_id'))
    )
    op.create_index(op.f('ix_rounds_group_id'), 'rounds', ['group_id'], unique=False)
    op.create_table('teams',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['competition_groups.id'], name=op.f('fk_teams_group_id_competition_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teams')),
    sa.UniqueConstraint('group_id', 'external_id', name=op.f('uq_teams_group_id_external_id')),
    sa.UniqueConstraint('id', 'group_id', name=op.f('uq_teams_id_group_id'))
    )
    op.create_index(op.f('ix_teams_group_id'), 'teams', ['group_id'], unique=False)
    op.create_table('matches',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('round_id', sa.BigInteger(), nullable=False),
    sa.Column('home_team_id', sa.BigInteger(), nullable=False),
    sa.Column('away_team_id', sa.BigInteger(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('venue', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('scheduled','finished','postponed','suspended','cancelled','unknown')", name=op.f('ck_matches_status_valid')),
    sa.CheckConstraint('(home_score IS NULL) = (away_score IS NULL)', name=op.f('ck_matches_score_pair')),
    sa.CheckConstraint('home_score >= 0 AND away_score >= 0', name=op.f('ck_matches_score_non_negative')),
    sa.CheckConstraint('home_team_id <> away_team_id', name=op.f('ck_matches_home_away_differ')),
    sa.ForeignKeyConstraint(['away_team_id', 'group_id'], ['teams.id', 'teams.group_id'], name=op.f('fk_matches_away_team_id_group_id_teams')),
    sa.ForeignKeyConstraint(['group_id'], ['competition_groups.id'], name=op.f('fk_matches_group_id_competition_groups')),
    sa.ForeignKeyConstraint(['home_team_id', 'group_id'], ['teams.id', 'teams.group_id'], name=op.f('fk_matches_home_team_id_group_id_teams')),
    sa.ForeignKeyConstraint(['round_id', 'group_id'], ['rounds.id', 'rounds.group_id'], name=op.f('fk_matches_round_id_group_id_rounds')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_matches')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_matches_source_external_id'))
    )
    op.create_index('ix_matches_away_team_id', 'matches', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_matches_group_id'), 'matches', ['group_id'], unique=False)
    op.create_index('ix_matches_home_team_id', 'matches', ['home_team_id'], unique=False)
    op.create_index('ix_matches_round_id', 'matches', ['round_id'], unique=False)
    op.create_index('ix_matches_status', 'matches', ['status'], unique=False)
    op.create_table('match_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('(home_score IS NULL) = (away_score IS NULL)', name=op.f('ck_match_observations_score_pair')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_match_observations_ingestion_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_observations_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_observations'))
    )
    op.create_index(op.f('ix_match_observations_ingestion_run_id'), 'match_observations', ['ingestion_run_id'], unique=False)
    op.create_index('ix_match_observations_match_id_observed_at', 'match_observations', ['match_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_match_observations_match_id_observed_at', table_name='match_observations')
    op.drop_index(op.f('ix_match_observations_ingestion_run_id'), table_name='match_observations')
    op.drop_table('match_observations')
    op.drop_index('ix_matches_status', table_name='matches')
    op.drop_index('ix_matches_round_id', table_name='matches')
    op.drop_index('ix_matches_home_team_id', table_name='matches')
    op.drop_index(op.f('ix_matches_group_id'), table_name='matches')
    op.drop_index('ix_matches_away_team_id', table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_teams_group_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_rounds_group_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_competition_groups_competition_id'), table_name='competition_groups')
    op.drop_table('competition_groups')
    op.drop_index(op.f('ix_data_quality_issues_ingestion_run_id'), table_name='data_quality_issues')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_competitions_season_id'), table_name='competitions')
    op.drop_table('competitions')
    op.drop_table('seasons')
    op.drop_table('ingestion_runs')
    # ### end Alembic commands ###
