"""actas de partido: informes, jugadores, participaciones, staff, oficiales y eventos

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-05 16:32:19.953339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_players_source_external_id'))
    )
    op.create_table('player_team_memberships',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('season_id', sa.BigInteger(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_player_team_memberships_player_id_players')),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], name=op.f('fk_player_team_memberships_season_id_seasons')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_player_team_memberships_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_team_memberships')),
    sa.UniqueConstraint('player_id', 'team_id', 'season_id', name=op.f('uq_player_team_memberships_player_id_team_id_season_id'))
    )
    op.create_index(op.f('ix_player_team_memberships_player_id'), 'player_team_memberships', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_team_memberships_season_id'), 'player_team_memberships', ['season_id'], unique=False)
    op.create_index(op.f('ix_player_team_memberships_team_id'), 'player_team_memberships', ['team_id'], unique=False)
    op.create_table('match_reports',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], name=op.f('fk_match_reports_match_id_matches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_reports')),
    sa.UniqueConstraint('match_id', name=op.f('uq_match_reports_match_id')),
    sa.UniqueConstraint('source', 'external_id', name=op.f('uq_match_reports_source_external_id'))
    )
    op.create_table('match_report_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('ingestion_run_id', sa.BigInteger(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('round_external_id', sa.String(length=64), nullable=False),
    sa.Column('home_team_external_id', sa.String(length=64), nullable=True),
    sa.Column('away_team_external_id', sa.String(length=64), nullable=True),
    sa.Column('home_formation', sa.String(length=32), nullable=True),
    sa.Column('away_formation', sa.String(length=32), nullable=True),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('venue', sa.String(length=256), nullable=True),
    sa.CheckConstraint('(home_score IS NULL) = (away_score IS NULL)', name=op.f('ck_match_report_observations_score_pair')),
    sa.ForeignKeyConstraint(['ingestion_run_id'], ['ingestion_runs.id'], name=op.f('fk_match_report_observations_ingestion_run_id_ingestion_runs')),
    sa.ForeignKeyConstraint(['report_id'], ['match_reports.id'], name=op.f('fk_match_report_observations_report_id_match_reports')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_report_observations')),
    sa.UniqueConstraint('report_id', 'content_hash', name=op.f('uq_match_report_observations_report_id_content_hash'))
    )
    op.create_index(op.f('ix_match_report_observations_ingestion_run_id'), 'match_report_observations', ['ingestion_run_id'], unique=False)
    op.create_index('ix_match_report_observations_report_id_observed_at', 'match_report_observations', ['report_id', 'observed_at'], unique=False)
    op.create_table('match_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=16), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('player_external_id', sa.String(length=64), nullable=True),
    sa.Column('player_name', sa.String(length=256), nullable=True),
    sa.Column('minute', sa.Integer(), nullable=True),
    sa.Column('source_code', sa.String(length=32), nullable=True),
    sa.Column('source_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint("event_type IN ('goal','card')", name=op.f('ck_match_events_type_valid')),
    sa.CheckConstraint('minute IS NULL OR minute >= 0', name=op.f('ck_match_events_minute_non_negative')),
    sa.ForeignKeyConstraint(['observation_id'], ['match_report_observations.id'], name=op.f('fk_match_events_observation_id_match_report_observations')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_events_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_events_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_events')),
    sa.UniqueConstraint('observation_id', 'sequence', name=op.f('uq_match_events_observation_id_sequence'))
    )
    op.create_index(op.f('ix_match_events_observation_id'), 'match_events', ['observation_id'], unique=False)
    op.create_index(op.f('ix_match_events_player_id'), 'match_events', ['player_id'], unique=False)
    op.create_index(op.f('ix_match_events_team_id'), 'match_events', ['team_id'], unique=False)
    op.create_table('match_officials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['match_report_observations.id'], name=op.f('fk_match_officials_observation_id_match_report_observations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_officials')),
    sa.UniqueConstraint('observation_id', 'sequence', name=op.f('uq_match_officials_observation_id_sequence'))
    )
    op.create_index(op.f('ix_match_officials_observation_id'), 'match_officials', ['observation_id'], unique=False)
    op.create_table('match_players',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=False),
    sa.Column('player_id', sa.BigInteger(), nullable=True),
    sa.Column('player_external_id', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('shirt_number', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('lineup_status', sa.String(length=16), nullable=False),
    sa.Column('is_captain', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.CheckConstraint("lineup_status IN ('starter','substitute','unknown')", name=op.f('ck_match_players_lineup_valid')),
    sa.CheckConstraint('shirt_number IS NULL OR shirt_number >= 0', name=op.f('ck_match_players_shirt_non_negative')),
    sa.ForeignKeyConstraint(['observation_id'], ['match_report_observations.id'], name=op.f('fk_match_players_observation_id_match_report_observations')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_match_players_player_id_players')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_players_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_players')),
    sa.UniqueConstraint('observation_id', 'team_id', 'sequence', name=op.f('uq_match_players_observation_id_team_id_sequence'))
    )
    op.create_index(op.f('ix_match_players_observation_id'), 'match_players', ['observation_id'], unique=False)
    op.create_index(op.f('ix_match_players_player_id'), 'match_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_match_players_team_id'), 'match_players', ['team_id'], unique=False)
    op.create_index('uq_match_players_observation_id_team_id_player_external_id', 'match_players', ['observation_id', 'team_id', 'player_external_id'], unique=True, postgresql_where=sa.text('player_external_id IS NOT NULL'))
    op.create_table('match_staff',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=False),
    sa.Column('team_id', sa.BigInteger(), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['match_report_observations.id'], name=op.f('fk_match_staff_observation_id_match_report_observations')),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name=op.f('fk_match_staff_team_id_teams')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_staff')),
    sa.UniqueConstraint('observation_id', 'sequence', name=op.f('uq_match_staff_observation_id_sequence'))
    )
    op.create_index(op.f('ix_match_staff_observation_id'), 'match_staff', ['observation_id'], unique=False)
    op.create_index(op.f('ix_match_staff_team_id'), 'match_staff', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_staff_team_id'), table_name='match_staff')
    op.drop_index(op.f('ix_match_staff_observation_id'), table_name='match_staff')
    op.drop_table('match_staff')
    op.drop_index('uq_match_players_observation_id_team_id_player_external_id', table_name='match_players', postgresql_where=sa.text('player_external_id IS NOT NULL'))
    op.drop_index(op.f('ix_match_players_team_id'), table_name='match_players')
    op.drop_index(op.f('ix_match_players_player_id'), table_name='match_players')
    op.drop_index(op.f('ix_match_players_observation_id'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_index(op.f('ix_match_officials_observation_id'), table_name='match_officials')
    op.drop_table('match_officials')
    op.drop_index(op.f('ix_match_events_team_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_player_id'), table_name='match_events')
    op.drop_index(op.f('ix_match_events_observation_id'), table_name='match_events')
    op.drop_table('match_events')
    op.drop_index('ix_match_report_observations_report_id_observed_at', table_name='match_report_observations')
    op.drop_index(op.f('ix_match_report_observations_ingestion_run_id'), table_name='match_report_observations')
    op.drop_table('match_report_observations')
    op.drop_table('match_reports')
    op.drop_index(op.f('ix_player_team_memberships_team_id'), table_name='player_team_memberships')
    op.drop_index(op.f('ix_player_team_memberships_season_id'), table_name='player_team_memberships')
    op.drop_index(op.f('ix_player_team_memberships_player_id'), table_name='player_team_memberships')
    op.drop_table('player_team_memberships')
    op.drop_table('players')
    # ### end Alembic commands ###
